# Generated by Django 3.1 on 2021-10-17 09:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('kind', models.CharField(max_length=128)),
                ('sell_type', models.CharField(max_length=128)),
                ('total_price', models.FloatField()),
                ('square', models.FloatField()),
                ('image', models.URLField(blank=True, null=True)),
                ('first_line', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Poly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('kind', models.CharField(max_length=64)),
            ],
        ),
    ]
