# Generated by Django 3.1 on 2021-10-17 12:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('live_humans_2021', models.IntegerField()),
                ('live_humans_2025', models.IntegerField()),
                ('live_humans_2030', models.IntegerField()),
                ('work_humans', models.IntegerField()),
                ('transports', models.IntegerField()),
                ('colors', models.JSONField()),
            ],
        ),
    ]
