# Generated by Django 3.1 on 2021-10-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poly',
            name='kind',
        ),
        migrations.AddField(
            model_name='poly',
            name='colors',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poly',
            name='live_humans_2021',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poly',
            name='live_humans_2025',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poly',
            name='live_humans_2030',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poly',
            name='transports',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poly',
            name='work_humans',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
