# Generated by Django 3.1 on 2021-10-19 07:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20211019_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=512)),
                ('rating', models.IntegerField()),
                ('chief_name', models.CharField(max_length=256)),
                ('web_site', models.URLField()),
                ('pupils_cnt', models.IntegerField()),
                ('nagruzka', models.IntegerField()),
                ('nagruzka_2025year', models.IntegerField()),
            ],
        ),
    ]
