# Generated by Django 3.1 on 2021-10-22 07:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20211019_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='poly',
            name='polygon_3857',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=3857),
        ),
    ]
