# Generated by Django 3.1 on 2021-10-22 09:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_poly_polygon_3857'),
    ]

    operations = [
        migrations.AddField(
            model_name='poly',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
