# Generated by Django 3.1 on 2021-11-02 16:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_poly_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poly',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='poly',
            name='polygon_3857',
        ),
        migrations.AlterField(
            model_name='poly',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
