# Generated by Django 3.1 on 2021-11-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20211102_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='poly',
            name='new_sc_rat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poly',
            name='new_school',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poly',
            name='potr_rat25',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poly',
            name='potreb_rat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poly',
            name='share_buil',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poly',
            name='transport',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
