# Generated by Django 3.1 on 2021-11-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20211105_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='nagruzka_rat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='nagruzka_rat_5year',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
