# Generated by Django 3.1 on 2021-11-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20211105_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poly',
            name='optima',
        ),
    ]
